
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmtxnbpfwkamvpdsancn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtdHhuYnBmd2thbXZwZHNhbmNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MTY3ODcsImV4cCI6MjA2MDM5Mjc4N30.S46LPErfUCTjYCFQN8UM90fNY5jMwfsFyH4yHCL5r8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true
  },
  global: {
    headers: {
      'x-application-name': 'collabdoor'
    }
  }
});

// Storage buckets for the application
export const storageBuckets = {
  profiles: 'profiles',
  projects: 'projects',
  organizations: 'organizations',
  proposals: 'proposals'
};
